name: gc9a01-tft
description:  Driver for the GC9A01 18 bit TFT color display controller.
environment:
  sdk: ^2.0.0-alpha.121
dependencies:
  color-tft:
    url: github.com/toitware/toit-color-tft
    version: ^2.1.0
